---

- name: retrieve XML of libvirt cluster network
  community.libvirt.virt_net:
    command: get_xml
    name: '{{ cluster_id }}'
  register: libvirt_cluster_network

- name: determine network configuration for cluster nodes
  community.general.xml:
    xmlstring: '{{ libvirt_cluster_network.get_xml }}'
    xpath: /network/ip/dhcp/host
    content: attribute
  register: libvirt_cluster_nodes

- name: add cluster nodes to SSH configuration for user root
  ansible.builtin.blockinfile:
    path: '~root/.ssh/config'
    block: '{{ lookup("template", "{{ role_path }}/templates/ssh-config.j2") }}'
    create: true
    owner: root
    group: root
    mode: '0644'

- name: set /etc/hosts cluster nodes fact
  ansible.builtin.set_fact:
    cluster_nodes_etc_hosts: '{{ (cluster_nodes_etc_hosts | default([])) + [item.host.ip + " " + item.host.name.split(".")[0]] }}'
  loop: '{{ libvirt_cluster_nodes.matches }}'
  when: not "bootstrap" in item.host.name

- name: add cluster nodes to /etc/hosts
  ansible.builtin.blockinfile:
    path: /etc/hosts
    marker: '{{ libvirt_marker }}'
    block: "{{ cluster_nodes_etc_hosts | join('\n') }}"
