---

# settings for all Ansible hosts

# Ansible-specific settings

ansible_python_interpreter: '/usr/bin/python3'

ansible_ssh_common_args: >
  -o IdentitiesOnly=yes
  -o BatchMode=yes
  -o UserKnownHostsFile=/dev/null
  -o StrictHostKeyChecking=no

ansible_user: root

# OpenShift-specific default settings

openshift_installer_workdir: /root/ocp4-workdir

openshift_network_type: OpenShiftSDN

machine_network_prefix: 192.168.126
machine_network_master_range: 10
machine_network_worker_range: 50

cluster_network: '10.128.0.0/14'
cluster_network_hostprefix: 23

service_networks:
  - 172.30.0.0/16

cluster_waiting_period: 600
