---

apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tune-ocp-kvm-host
spec:
  params:
  - description: Name of the target KVM host whose OCP cluster will be tuned
    name: host
    type: string
  - description: URL of the git repository containing the cluster configuration data
    name: configs-url
    type: string
  - description: Name of the git repository branch from which to fetch cluster configuration data
    name: configs-branch
    type: string
    default: main
  tasks:
  - name: fetch-config
    params:
    - name: url
      value: $(params.configs-url)
    - name: revision
      value: $(params.configs-branch)
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: configs
  - name: kvm-run-playbook
    params:
    - name: host
      value: $(params.host)
    - name: playbook
      value: tune_ocp_install.yml
    runAfter:
    - fetch-config
    taskRef:
      kind: Task
      name: kvm-run-playbook
    timeout: "2h"
    workspaces:
    - name: configs
      workspace: configs
  finally:
  - name: cluster-reconcile-sleep
    params:
    - name: duration
      value: "300"
    taskRef:
      kind: Task
      name: sleep
  workspaces:
  - name: configs
