---

- name: disable modular libvirt (RHEL 9 only)
  ansible.builtin.systemd:
    name: '{{ item }}'
    state: stopped
    enabled: false
    masked: true
  loop: '{{ libvirt_modular["services"] + libvirt_modular["sockets"] }}'
  when:
    - "ansible_distribution_major_version == '9'"
    - "ansible_distribution == 'RedHat'"

- name: enable and start libvirtd-tcp.socket service
  ansible.builtin.service:
    name: libvirtd-tcp.socket
    state: started
    enabled: true

- name: disable auth_tcp for libvirtd
  ansible.builtin.replace:
    path: /etc/libvirt/libvirtd.conf
    regexp: '^#(auth_tcp.*)'
    replace: 'auth_tcp = "none"'
    backup: true

- name: enable libvirtd service
  ansible.builtin.service:
    name: '{{ item }}'
    state: started
    enabled: true
  loop: '{{ libvirt_monolithic["services"] }}'
