---

- name: enable IPv4 forwarding
  ansible.posix.sysctl:
    name: '{{ item }}'
    value: '1'
    sysctl_set: true
    state: present
    reload: true
  loop:
    - net.ipv4.conf.all.arp_filter
    - net.ipv4.conf.all.proxy_arp
    - net.ipv4.conf.all.forwarding
    - net.ipv4.ip_forward

- name: enable monolithic libvirt
  ansible.builtin.include_tasks: '{{ role_path }}/tasks/enable_monolithic_libvirt.yml'

- name: set the default libvirt connection URI
  ansible.builtin.copy:
    src: '{{ role_path }}/files/libvirt.profile.sh'
    dest: /etc/profile.d/libvirt.sh
    owner: root
    group: root
    mode: '0644'
