---

- name: enable non-local IPv4 port bindings
  ansible.posix.sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: '1'
    sysctl_set: true
    state: present
    reload: true

- name: ensure haproxy package is present
  ansible.builtin.dnf:
    name: haproxy
    state: present

- name: stop haproxy service
  ansible.builtin.service:
    name: haproxy
    state: stopped
    enabled: true

- name: configure haproxy
  ansible.builtin.blockinfile:
    path: /etc/haproxy/haproxy.cfg
    marker: '{{ item.marker | default(omit) }}'
    block: '{{ item.block }}'
  loop:
    - { 'block': '' }
    - { 'marker': '{{ host_marker }}', 'block': '' }
    - { 'marker': '{{ host_marker }}', 'block': '{{ lookup("template", "{{ role_path }}/templates/haproxy.cfg.j2") }}' }
