---

galaxy_info:
  role_name: ocp_install_clients
  author: Dirk Haubenreisser (haubenr@de.ibm.com)
  description: Role performing the installation of OpenShift client binaries
  company: IBM
  license: Apache
  min_ansible_version: 2.10
  platforms:
    - name: EL
      versions: 8
