---

- name: configure SELinux
  block:
    - name: set to permissive mode
      ansible.posix.selinux:
        policy: targeted
        state: permissive
      when: ansible_selinux.status == 'enabled'

    - name: enable haproxy connectivity
      ansible.posix.seboolean:
        name: haproxy_connect_any
        state: true
        persistent: true
      when: ansible_selinux.status == 'enabled'
