---

- name: enable the use of crypto resources for the OpenShift cluster (s390x only)
  hosts: s390x_kvm_host
  vars:
    skip_libvirt_soundness_check: true
  roles:
    - role: soundness_check
      when: disable_soundness_check is undefined
      tags:
        - soundness
        - preflight

    - role: crypto
      when: crypto_adapters is defined
      tags:
        - crypto
  tasks:
    - name: display final message
      when: crypto_adapters is defined
      ansible.builtin.debug:
        msg:
          - "Finished enabling crypto resources for the KVM-based OpenShift cluster on host '{{ inventory_hostname }}'. All done."
          - "Enjoy!"

    - name: display final message
      when: crypto_adapters is undefined
      ansible.builtin.debug:
        msg:
          - "No crypto resource configuration has been provided for host '{{ inventory_hostname }}'. Nothing to be done."
          - "Enjoy!"
