---

- name: prepare the KVM-based OpenShift cluster installation
  hosts: s390x_kvm_host,ppc64le_kvm_host,x86_64_kvm_host,aarch64_kvm_host
  roles:
    - role: soundness_check
      when: disable_soundness_check is undefined
      tags:
        - soundness
        - preflight

    - role: ocp_prepare_install
      tags:
        - prepare

    - role: ocp_build_installer
      tags:
        - prepare
        - build

    - role: ocp_install_clients
      tags:
        - prepare
        - clients
  tasks:
    - name: display final message
      ansible.builtin.debug:
        msg: "Finished preparing the KVM-based OpenShift cluster installation via IPI on host '{{ inventory_hostname }}'. All done."
