---

- name: provision additional worker nodes for the OpenShift cluster
  hosts: s390x_kvm_host,ppc64le_kvm_host,x86_64_kvm_host,aarch64_kvm_host
  vars:
    skip_libvirt_soundness_check: true
  roles:
    - role: ocp_provision_nodes
      vars:
        cluster_node_type: worker
      tags:
        - worker
  tasks:
    - name: display final message
      ansible.builtin.debug:
        msg: "Finished provisioning additional worker nodes for the KVM-based OpenShift cluster on host '{{ inventory_hostname }}'. All done."
