---

- name: install the KVM-based OpenShift cluster
  hosts: s390x_kvm_host,ppc64le_kvm_host,x86_64_kvm_host,aarch64_kvm_host
  pre_tasks:
    - name: check the cluster image pull secret file exists on the Ansible controller
      block:
        - name: get pull secret file stats
          ansible.builtin.stat:
            path: '{{ cluster_pull_secret_file }}'
          register: pull_secret_file_info
          delegate_to: localhost

        - name: display playbook usage message
          when: not pull_secret_file_info.stat.exists
          ansible.builtin.fail:
            msg:
              - "The cluster image pull secret file does not exist."
              - "Make sure it's present at the following location before running this playbook:"
              - "{{ cluster_pull_secret_file }}"

    - name: check if vbmc and ipmi support is to be configured for the cluster
      ansible.builtin.set_fact:
        vbmc_ipmi: '{{ setup_vbmc_ipmi | default(true) }}'

    - name: check if the cluster is to be installed in FIPS mode
      ansible.builtin.set_fact:
        fips_mode: '{{ openshift_setup_fips_mode | default(false) }}'

  roles:
    - role: soundness_check
      when: disable_soundness_check is undefined
      tags:
        - soundness
        - preflight

    - role: ocp_install_cluster
      tags:
        - install

    - role: ocp_install_cluster_wrapup
      tags:
        - install
        - wrapup

    - role: vbmc
      tags:
        - vbmc
      when: vbmc_ipmi

  tasks:
    - name: display final message
      ansible.builtin.debug:
        msg:
          - "Finished installing the KVM-based OpenShift cluster via IPI on host '{{ inventory_hostname }}'. All done."
          - "You can use 'oc' directly from the root user's account to interact with the cluster."
          - "Enjoy!"
