---

- name: run soundness checks
  hosts: s390x_kvm_host,ppc64le_kvm_host,x86_64_kvm_host,aarch64_kvm_host
  vars:
    skip_libvirt_soundness_check: true
  roles:
    - role: soundness_check
      tags:
        - soundness
        - preflight
  tasks:
    - name: display final message
      ansible.builtin.debug:
        msg: "Finished running soundness checks for KVM host '{{ inventory_hostname }}'. All done."
