---

- name: setup the KVM host
  hosts: s390x_kvm_host,ppc64le_kvm_host,x86_64_kvm_host,aarch64_kvm_host
  vars:
    skip_libvirt_soundness_check: true
  roles:
    - role: soundness_check
      when: disable_soundness_check is undefined
      tags:
        - soundness
        - preflight

    - role: basics
      tags:
        - setup
        - basics

    - role: selinux
      tags:
        - setup
        - selinux

    - role: libvirt
      tags:
        - setup
        - libvirt

    - role: networking
      tags:
        - setup
        - networking

    - role: firewall
      tags:
        - setup
        - firewall
  tasks:
    - name: display final message
      ansible.builtin.debug:
        msg: "Finished setting up the KVM host '{{ inventory_hostname }}'. All done."
