---

galaxy_info:
  role_name: ocp_install_cluster_wrapup
  author: Dirk Haubenreisser (haubenr@de.ibm.com)
  description: Role performing setup and configuration tasks after the RHOCP cluster installation has finished
  company: IBM
  license: Apache-2.0
  min_ansible_version: "2.10"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
