name: Docker image build and push

on:
  push:
    branches:
      - main

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v2
      - name: set up QEMU for Docker buildx
        uses: docker/setup-qemu-action@v1
      - name: set up Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_ACCESS_TOKEN }}
      - name: build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          tags: ${{ github.repository_owner }}/${{ github.repository }}:latest
          cache-from: type=registry,ref=${{ github.repository_owner }}/${{ github.repository }}:buildcache
          cache-to: type=registry,ref=${{ github.repository_owner }}/${{ github.repository }}:buildcache,mode=max
